name: vow_society
description: The Vow Society - Wedding Venue Marketplace
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: any

  # UI Components
  cupertino_icons: any
  google_fonts: ^6.3.2
  cached_network_image: any
  flutter_svg: any

  # Maps & Location
  google_maps_flutter: any
  geolocator: any
  geocoding: any

  # Backend & API
  supabase_flutter: any
  http: ^1.5.0

  # Navigation
  go_router: any

  # Storage & Cache
  shared_preferences: any
  hive: any
  hive_flutter: any

  # Utilities
  intl: any
  uuid: any
  url_launcher: any
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  hive_generator: any
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
