name = "vows-social-email-worker"
main = "email-worker.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
SUPABASE_URL = "https://nidbhgqeyhrudtnizaya.supabase.co"

# Secrets (set via: wrangler secret put SUPABASE_ANON_KEY)
# SUPABASE_ANON_KEY = (set as secret)
